import type { CropListing } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const defaultCrops: Omit<CropListing, 'farmerId'>[] = [
  {
    id: 'crop-1',
    cropType: 'Wheat',
    quantity: 50,
    price: 300,
    location: 'Punjab, India',
    city: 'Amritsar',
    country: 'India',
    images: [
      { id: 'img-1', imageUrl: 'https://picsum.photos/seed/wheat1/600/400', imageHint: 'wheat field' },
      { id: 'img-2', imageUrl: 'https://picsum.photos/seed/wheat2/600/400', imageHint: 'wheat grain' },
      { id: 'img-3', imageUrl: 'https://picsum.photos/seed/wheat3/600/400', imageHint: 'harvest wheat' },
    ],
    qualityNotes: 'Excellent grain uniformity and low moisture content. Certified organic.',
    status: 'Listed',
    aiVerified: true,
    listingDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-2',
    cropType: 'Basmati Rice',
    quantity: 100,
    price: 1200,
    location: 'Haryana, India',
    city: 'Karnal',
    country: 'India',
    images: [
      { id: 'img-4', imageUrl: 'https://picsum.photos/seed/rice1/600/400', imageHint: 'rice paddy' },
      { id: 'img-5', imageUrl: 'https://picsum.photos/seed/rice2/600/400', imageHint: 'rice grain' },
      { id: 'img-6', imageUrl: 'https://picsum.photos/seed/rice3/600/400', imageHint: 'sacks rice' },
    ],
    qualityNotes: 'Aged for 2 years, resulting in a distinct aroma and fluffy texture when cooked. A-grade quality.',
    status: 'Listed',
    aiVerified: true,
    listingDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-3',
    cropType: 'Corn',
    quantity: 200,
    price: 250,
    location: 'Iowa, USA',
    city: 'Des Moines',
    country: 'United States',
    images: [
      { id: 'img-7', imageUrl: 'https://picsum.photos/seed/corn1/600/400', imageHint: 'corn field' },
      { id: 'img-8', imageUrl: 'https://picsum.photos/seed/corn2/600/400', imageHint: 'corn cob' },
      { id: 'img-9', imageUrl: 'https://picsum.photos/seed/corn3/600/400', imageHint: 'corn harvest' },
    ],
    qualityNotes: 'Sweet corn variety, ideal for direct consumption or processing. Non-GMO.',
    status: 'Listed',
    aiVerified: true,
    listingDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-4',
    cropType: 'Soybean',
    quantity: 150,
    price: 450,
    location: 'Mato Grosso, Brazil',
    city: 'Cuiabá',
    country: 'Brazil',
    images: [
      { id: 'img-10', imageUrl: 'https://picsum.photos/seed/soy1/600/400', imageHint: 'soybean field' },
      { id: 'img-11', imageUrl: 'https://picsum.photos/seed/soy2/600/400', imageHint: 'soybean plant' },
      { id: 'img-12', imageUrl: 'https://picsum.photos/seed/soy3/600/400', imageHint: 'soybean harvest' },
    ],
    qualityNotes: 'High-protein soybeans, suitable for feed and oil production. Sustainably farmed.',
    status: 'Listed',
    aiVerified: false,
    listingDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-5',
    cropType: 'Barley',
    quantity: 80,
    price: 280,
    location: 'Alberta, Canada',
    city: 'Calgary',
    country: 'Canada',
    images: [
      { id: 'img-13', imageUrl: 'https://picsum.photos/seed/barley1/600/400', imageHint: 'barley field' },
      { id: 'img-14', imageUrl: 'https://picsum.photos/seed/barley2/600/400', imageHint: 'barley grain' },
      { id: 'img-15', imageUrl: 'https://picsum.photos/seed/barley3/600/400', imageHint: 'barley harvest' },
    ],
    qualityNotes: 'High-quality malting barley, perfect for craft brewing. Low protein content.',
    status: 'Listed',
    aiVerified: false,
    listingDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
