import type { CropListing } from './types';

export const defaultCrops: Omit<CropListing, 'farmerId'>[] = [
  {
    id: 'crop-1',
    cropType: 'Wheat',
    quantity: 50,
    price: 300,
    location: 'Punjab, India',
    city: 'Amritsar',
    country: 'India',
    images: [
      'https://picsum.photos/seed/wheat1/600/400',
      'https://picsum.photos/seed/wheat2/600/400',
      'https://picsum.photos/seed/wheat3/600/400',
    ],
    qualityNotes: 'Excellent grain uniformity and low moisture content. Certified organic.',
    status: 'Listed',
    aiVerified: true,
    listingDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-2',
    cropType: 'Basmati Rice',
    quantity: 100,
    price: 1200,
    location: 'Haryana, India',
    city: 'Karnal',
    country: 'India',
    images: [
      'https://picsum.photos/seed/rice1/600/400',
      'https://picsum.photos/seed/rice2/600/400',
      'https://picsum.photos/seed/rice3/600/400',
    ],
    qualityNotes: 'Aged for 2 years, resulting in a distinct aroma and fluffy texture when cooked. A-grade quality.',
    status: 'Listed',
    aiVerified: true,
    listingDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-3',
    cropType: 'Corn',
    quantity: 200,
    price: 250,
    location: 'Iowa, USA',
    city: 'Des Moines',
    country: 'United States',
    images: [
      'https://picsum.photos/seed/corn1/600/400',
      'https://picsum.photos/seed/corn2/600/400',
      'https://picsum.photos/seed/corn3/600/400',
    ],
    qualityNotes: 'Sweet corn variety, ideal for direct consumption or processing. Non-GMO.',
    status: 'Listed',
    aiVerified: true,
    listingDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-4',
    cropType: 'Soybean',
    quantity: 150,
    price: 450,
    location: 'Mato Grosso, Brazil',
    city: 'Cuiabá',
    country: 'Brazil',
    images: [
      'https://picsum.photos/seed/soy1/600/400',
      'https://picsum.photos/seed/soy2/600/400',
      'https://picsum.photos/seed/soy3/600/400',
    ],
    qualityNotes: 'High-protein soybeans, suitable for feed and oil production. Sustainably farmed.',
    status: 'Listed',
    aiVerified: false,
    listingDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'crop-5',
    cropType: 'Barley',
    quantity: 80,
    price: 280,
    location: 'Alberta, Canada',
    city: 'Calgary',
    country: 'Canada',
    images: [
      'https://picsum.photos/seed/barley1/600/400',
      'https://picsum.photos/seed/barley2/600/400',
      'https://picsum.photos/seed/barley3/600/400',
    ],
    qualityNotes: 'High-quality malting barley, perfect for craft brewing. Low protein content.',
    status: 'Listed',
    aiVerified: false,
    listingDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
